### ISSUE TITLE
[BUG] Clicking on a blank space when loading a level in the editor crashes the game

### ISSUE THREAD

**Issue by Kamerson** [HumanGamer/WPlusIssues#62] opened 2022-07-16 05:50 UTC
In the W+ editor, if you click on Load Level and you click on any empty space below the levels, the following crash will occur:
![image](https://user-images.githubusercontent.com/6343501/179341887-72a5463f-8275-4167-b02a-d517a09419aa.png)

**Comment by ALEXM99999** [comment] 2022-07-16 09:56
Fixed on commit 384e3e1e. (also duplicate of 59)

**Closed as completed by ALEXM99999** 2022-07-16 09:56 UTC
Labels: bug

**Comment by Kamerson** [comment] 2022-07-16 13:54
> Fixed on commit 384e3e1e. (also duplicate of 59)

Oh oops, sorry! I didn't look to see if the issue was already posted >.<
