### ISSUE TITLE
[BUG] Riding a switchable conveyor into water keeps the conveyor switching back and forth

### ISSUE THREAD

**Issue by Kamerson** [HumanGamer/WPlusIssues#31] opened 2022-01-19 01:19 UTC
If you step on a switchable conveyor and ride it into water (or any other unopen tile that ends in your death), the switchable conveyor will keep switching back and forth when you're dieing. In the vanilla game, this does not happen; the conveyor switches only once after riding into the water.

**Comment by ALEXM99999** [comment] 2022-04-01 22:28
The cause for that was the same as the crash in this https://github.com/HumanGamer/WPlusIssues/issues/32 so this is fixed now as well

**Closed as completed by ALEXM99999** 2022-04-01 22:28 UTC
Labels: bug
