### ISSUE TITLE
[BUG] Playground (FIXED) and some WSW levels (NOT FIXED) crash the game

### ISSUE THREAD

**Issue by myuacc1** [HumanGamer/WPlusIssues#29] opened 2022-01-15 20:38 UTC
I tried playing some of the Playground levels, and I keep getting this message:
![wampwampwampwaaaaaamp](https://user-images.githubusercontent.com/97628479/149636872-9f18c986-2f0e-40ee-9604-02f27ae9dcfb.png)

After which, W+ closes.

Another simular situation happend when I tried playing "The Old Windmill", exepct I got no error and the game just suddenly closes. Do all of the WSW Rainbow Star levels crash the game too?

Both of these errors really need to be fixed...

**Comment by ALEXM99999** [comment] 2022-01-19 00:43
I identified the first bug with the playground levels but couldn't reproduce the bug with The Old Windmill, can you share more details on how to reproduce it? Or was it random and happened only once?
Thanks!

**Comment by myuacc1** [comment] 2022-03-30 23:00
Sorry it took so long, but the Old Windmill bug keeps happening to me everytime I try to play it.

Here is some video I provived of the crash (I press Enter around 0:13-14):

https://user-images.githubusercontent.com/97628479/160944645-6a40f97c-9d22-4a50-a008-17fc08666a1b.mp4

**Comment by ALEXM99999** [comment] 2022-03-30 23:55
Thanks for the video! Does this happen with other rainbow levels as well?

**Comment by myuacc1** [comment] 2022-03-31 06:23
I haven't gotten to any of those yet, but it also seems that "The Town Square" is another level that crashes on me when I press enter, as seen in this next video (I press enter around 0:10, much quicker crash than The Old Windmill):

https://user-images.githubusercontent.com/97628479/160989580-1b45c638-e642-45df-b5d9-c08d86b547fd.mp4

I'm gonna check to see if there are other WSW levels that crash on W+.

**Comment by myuacc1** [comment] 2022-03-31 06:38
"Somewhere on the edge of Wondertown...", "Ocean View Harbor" and "Through the Maze" are all levels confirmed to crash the game. With Creepy Keep requiring 5 stars to unlock, and me only being able to collect 3 stars and a rainbow star ("The Lost Cave" works for me...), WSW on W+ is currently practically unbeatable for me.

**Comment by ALEXM99999** [comment] 2022-03-31 13:49
Well all those levels actually use custom models and I forgot to put the models in the game data... sorry. However even without the models the game doesn't crash in my case, it just displays a placeholder model which means that still something is wrong here.

I have uploaded the models here, can you place them in he custom models directory and test again? Thanks
[CustomModels.zip](https://github.com/HumanGamer/WPlusIssues/files/8389973/CustomModels.zip)

**Comment by ALEXM99999** [comment] 2022-07-16 09:59
This seems to have been fixed, so I'll close this for now.

**Closed as completed by ALEXM99999** 2022-07-16 09:59 UTC
Labels: bug
